# repo config
repo_name: 'cloudfoundry/docs-cfcr'
repo_url: 'https://github.com/cloudfoundry/docs-cfcr'
edit_uri: edit/master/docs/
site_name: CFCR
site_dir: site/cfcr
theme: 'material'
theme_dir: 'theme-overrides'
site_favicon: favicon.ico

# left nav
pages:
  - Overview:
    - 'Welcome to CFCR': 'index.md'
    - 'Release Notes': 'overview/release-notes.md'

# palette, logo, css, markdown extensions
extra:
  palette:
    primary: 'teal'
    accent: 'deep orange'
  logo: 'images/common/cfcr-logo.png'
  feature:
    tabs: true
extra_css:
    - 'css/highlight-fix.css'
    - 'css/solarized_dark.css'
    - 'css/extras.css'
    # - 'css/all.css'
    # - 'css/print.css'
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(linenums=true)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
